name: Merge Pull Request Automatically

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge Pull Request
        uses: styfle/git-merge-pr@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ github.event.pull_request.head.ref }}