name: Merge Pull Request Automatically

on:
  push:
    branches:
      - development
    types: [pushed]

jobs:
  merge:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '--automerge')
    steps:
      - uses: actions/checkout@v3
      - name: Merge Development to Master
        uses: styfle/git-merge-pr@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: development